name    'ft-public_concordances_api'
version '0.0.0'
source 'git@github.com:Financial-Times/public-concordances-api.git'
author 'ft'
license 'Apache License, Version 2.0'
summary 'Provides a public API for users to lookup an concordance'
description 'Public API for retrieving information about an concordance'
project_page 'https://github.com/Financial-Times/public-concordances-api'

## Add dependencies, if any:
dependency 'ft/go_service_profile', '>= 0.0.0'
